// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5qaEELg9FCvxgWzXZc-1NIPLNuVRQ2Mc',
    appId: '1:940751296025:web:c61f9e2f5b4b8d8d807c88',
    messagingSenderId: '940751296025',
    projectId: 'sigbd-da7ad',
    authDomain: 'sigbd-da7ad.firebaseapp.com',
    storageBucket: 'sigbd-da7ad.firebasestorage.app',
    measurementId: 'G-FPMNNJD0FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUJNQ8RiV3yhXpfp35Zl_J_nNt--YTthg',
    appId: '1:940751296025:android:dfe8e738229404f1807c88',
    messagingSenderId: '940751296025',
    projectId: 'sigbd-da7ad',
    storageBucket: 'sigbd-da7ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFKsOyLhyZB2pQwgkFCXazqSXT-PTBqcY',
    appId: '1:940751296025:ios:f690ad6e00bcf63d807c88',
    messagingSenderId: '940751296025',
    projectId: 'sigbd-da7ad',
    storageBucket: 'sigbd-da7ad.firebasestorage.app',
    iosBundleId: 'com.example.sigTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFKsOyLhyZB2pQwgkFCXazqSXT-PTBqcY',
    appId: '1:940751296025:ios:f690ad6e00bcf63d807c88',
    messagingSenderId: '940751296025',
    projectId: 'sigbd-da7ad',
    storageBucket: 'sigbd-da7ad.firebasestorage.app',
    iosBundleId: 'com.example.sigTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5qaEELg9FCvxgWzXZc-1NIPLNuVRQ2Mc',
    appId: '1:940751296025:web:3280188fcfa9efe7807c88',
    messagingSenderId: '940751296025',
    projectId: 'sigbd-da7ad',
    authDomain: 'sigbd-da7ad.firebaseapp.com',
    storageBucket: 'sigbd-da7ad.firebasestorage.app',
    measurementId: 'G-GBGYJ8NJNH',
  );
}
